dict_sitios = {'7veinte':'7veinte',
                'sieteveintecl':'7veinte',
                'Azaleia':'Azaleia',
                'azaleiacl':'Azaleia',
                'Billabong':'Billabong',
                'billabongcl':'Billabong',
                'Body &amp; Soul':'BodyandSoul',
                'bodyandsoulcl':'BodyandSoul',
                'brookscl':'Brooks',
                'Burton':'Burton',
                'burtoncl':'Burton',
                'calpanycl':'Calpany',
                'Cat.cl':'Cat',
                'catcl':'Cat',
                'Store Cat.cl':'Cat',
                'Columbia Chile':'Columbia',
                'columbiacl':'Columbia',
                'Store Columbia Chile':'Columbia',
                'CX':'CX',
                'Hushpuppies':'Hushpuppies',
                'hushpuppiescl':'Hushpuppies',
                'Hushpuppies Kids':'Hushpuppies Kids',
                'hushpuppieskidscl':'Hushpuppies Kids',
                'JanSport.cl':'JanSport',
                'jansportcl':'JanSport',
                'Keds':'Keds',
                'kedscl':'Keds',
                'Merrell.cl':'Merrell',
                'merrellcl':'Merrell',
                'Store Merrell.cl':'Merrell',
                'MHW':'MHW',
                'Mountain Hardwear Chile':'MHW',
                'mountainhardwearcl':'MHW',
                'Nine West':'Nine West',
                'Norseg':'Norseg',
                'norsegcl':'Norseg',
                'Rockford':'Rockford',
                'rockfordcl':'Rockford',
                'underarmourcl':'Under Armor',
                'vanscl':'Vans',
                'weloveshoescl':'WeLoveShoes',
                'Zapatillas':'Zapatillas',
                'Zapatos.cl':'Zapatos',
                'zapatoscl':'Zapatos',
                'Zapatos.cl HP':'Zapatos_hp',
                'Zapatos.cl HPK':'Zapatos_hpk'}

dict_correos = {'list_email': ['7veinte','7veintevaldivia','azaleia','backoffice','billabong','bodyandsoul','cat','clb','columbia','columbiaforus','forus500','forus540','forusapp','funsport','hp91a5','hk50tienda','hk','hp.520','hp.malldelcentro','hp','jansport','mll','nnnn','nw.estado','rfvaldivia','rf.valdivia','rkf.valdivia','rkfvaldivia','rockford','wl','wls','www','','welove', 'az','bk','cl','dh','fs','hk','hp','kh','nw','ph','rf','rk','se','wl','bll','cat','clb','clv','dh.','mhw','mll','hkh','lcb','rfk','rkf','wls'],
                'forus_email': ['forus.cl'],
               'trash_email':['0000','1.','1','1','1051325564','1171785255','11997744zz','121324275','123','123_321','123321','1234','12345','123456','123456789','125','1456','147','246','2528.cl','258','53400365z','5jjml5','61546155','703','85','852','8521','856','95','964403630i','9852','a.','a','a','aa','aa','aaa','aaa','aaaa','aaaaa','ab','ab','ab260219', 'nn', 'x', 'xxx', 'zzz600b', 'zzzz', 'zzzzz.aaaaa099999', 'zzzzzz'],
               'trash_mailpag':['00.cl', '123.cl','qq.com','aa.cl','yopmail.com']}